### ISSUE TITLE
[BUG] I am using CamelModel to run the CRAB agent on top of Groq

### ISSUE THREAD

**Issue by Dineshkumar-Anandan-ZS0367** [camel-ai/crab#44] opened 2024-10-05 11:50 UTC
### What version of camel are you using?

0.2.1

### Problem description

ValueError: Unexpected argument `logit_bias` is input into Groq model backend. 

### Reproducible example code

if __name__ == "__main__":
    benchmark = create_benchmark(template_benchmark_config)
    task, action_space = benchmark.start_task("0")
    env_descriptions = benchmark.get_env_descriptions()

    agent = SingleAgentPolicy(
        model_backend=CamelModel(
            "llama-3.1-70b-versatile",
            model_platform='groq',
            parameters={
                "max_tokens": 8192,
                "temperature": 0.6,
                "top_p": 1.0,
                "n": 1,
                "stream": False,
                "presence_penalty": 0.0,
                "frequency_penalty": 0.0,
                "tool_choice": "auto",

            }
        )
    )

    agent.reset(task.description, action_space, env_descriptions)
    print("Start performing task: " + colored(f'"{task.description}"', "green"))
    start_benchmark(benchmark, agent)
    benchmark.reset()

**Comment by WHALEEYE** [comment] 2024-10-06 20:27
Hi @Dineshkumar-Anandan-ZS0367, thanks for your feedback! We have already located the problem, and we are fixing it. This should be done by the end of next week.

**Comment by WHALEEYE** [comment] 2024-10-08 22:28
Hi @Dineshkumar-Anandan-ZS0367, the problem is fixed in another branch and will be merged into the main branch soon through PR #45.
The CAMEL integration of CRAB is currently still unstable, and your feedback is really precious to us. Feel free to reach out when you meet other problems :)

**Comment by WHALEEYE** [comment] 2024-10-16 03:58
Hi @Dineshkumar-Anandan-ZS0367, since PR #45 has been merged we are closing this Issue. Thanks for your feedback!

**Closed by WHALEEYE** 2024-10-16 03:58 UTC
Labels: bug
